# ======================================================================
# ORIGINAL PYSPARK CODE
# ======================================================================

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, when, avg

# create spark session
spark = SparkSession.builder \
    .appName("PySpark Example") \
    .getOrCreate()

# sample data
data = [
    (1, "Alice", 25, 50000),
    (2, "Bob", 35, 80000),
    (3, "Charlie", 45, 120000),
    (4, "David", 29, 60000)
]

columns = ["id", "name", "age", "salary"]

df = spark.createDataFrame(data, columns)

# transformation
df_transformed = (
    df
    .withColumn(
        "age_group",
        when(col("age") < 30, "young")
        .when(col("age") < 40, "mid")
        .otherwise("senior")
    )
)

# aggregation
result = (
    df_transformed
    .groupBy("age_group")
    .agg(avg("salary").alias("avg_salary"))
)

# show output
result.show()

spark.stop()




# ======================================================================
# AUTO-GENERATED UNIT TESTS
# Generated by PySparkUnitTestGenAgent
# ======================================================================

# NOTE: To run these tests, save them to a separate file (e.g., test_*.py)
# and import the original code classes/functions as needed.


import pytest
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql import functions as F
from chispa.dataframe_comparer import assert_df_equality
from unittest.mock import Mock, patch, MagicMock


@pytest.fixture(scope="session")
def spark_session():
    """Create a SparkSession for testing"""
    spark = SparkSession.builder \
        .master("local[1]") \
        .appName("pytest") \
        .config("spark.driver.host", "localhost") \
        .getOrCreate()
    yield spark
    spark.stop()


# ======================================================================
# Tests for: main_script (Line 1)
# ======================================================================

@pytest.fixture
def sample_data(spark_session):
    """
    Fixture to create a sample DataFrame for testing.
    """
    data = [
        (1, "Alice", 25, 50000),
        (2, "Bob", 35, 80000),
        (3, "Charlie", 45, 120000),
        (4, "David", 29, 60000)
    ]
    columns = ["id", "name", "age", "salary"]
    return spark_session.createDataFrame(data, columns)

def test_transformation_age_group(sample_data):
    """
    Test the transformation logic for age_group column.
    """
    expected_data = [
        (1, "Alice", 25, 50000, "young"),
        (2, "Bob", 35, 80000, "mid"),
        (3, "Charlie", 45, 120000, "senior"),
        (4, "David", 29, 60000, "young")
    ]
    expected_columns = ["id", "name", "age", "salary", "age_group"]
    expected_df = spark_session.createDataFrame(expected_data, expected_columns)

    transformed_df = (
        sample_data
        .withColumn(
            "age_group",
            when(col("age") < 30, "young")
            .when(col("age") < 40, "mid")
            .otherwise("senior")
        )
    )

    assert_df_equality(transformed_df, expected_df)

def test_aggregation_avg_salary(sample_data):
    """
    Test the aggregation logic for average salary by age_group.
    """
    transformed_df = (
        sample_data
        .withColumn(
            "age_group",
            when(col("age") < 30, "young")
            .when(col("age") < 40, "mid")
            .otherwise("senior")
        )
    )

    result_df = (
        transformed_df
        .groupBy("age_group")
        .agg(avg("salary").alias("avg_salary"))
    )

    expected_data = [
        ("young", 55000.0),
        ("mid", 80000.0),
        ("senior", 120000.0)
    ]
    expected_columns = ["age_group", "avg_salary"]
    expected_df = spark_session.createDataFrame(expected_data, expected_columns)

    assert_df_equality(result_df, expected_df)

@pytest.mark.parametrize("data,expected", [
    ([], []),  # Empty DataFrame
    ([(1, "Alice", None, 50000)], [(1, "Alice", None, 50000, None)]),  # Null age
    ([(1, "Alice", 25, None)], [(1, "Alice", 25, None, "young")])  # Null salary
])
def test_edge_cases(data, expected, spark_session):
    """
    Test edge cases such as empty DataFrame, null values in age or salary.
    """
    columns = ["id", "name", "age", "salary"]
    input_df = spark_session.createDataFrame(data, columns)

    transformed_df = (
        input_df
        .withColumn(
            "age_group",
            when(col("age") < 30, "young")
            .when(col("age") < 40, "mid")
            .otherwise("senior")
        )
    )

    expected_columns = ["id", "name", "age", "salary", "age_group"]
    expected_df = spark_session.createDataFrame(expected, expected_columns)

    assert_df_equality(transformed_df, expected_df)

def test_error_handling_invalid_column(sample_data):
    """
    Test error handling when an invalid column is referenced.
    """
    with pytest.raises(Exception):
        sample_data.withColumn("invalid_column", col("non_existent_column"))